### ISSUE TITLE
script fails when launched from factorio-init with alt GLIBC

### ISSUE THREAD

**Issue by tmzasz** [Tantrisse/Factorio-mods-manager#7]
factorio init provides a way to declare an alternative GLIB c root as needed on redhat systems older than RHEL8/CentOS8. I am not fluent enough in python to add such a feature but it would be useful

**Comment by Tantrisse** [comment]
Hi, thx for the feedback !
I just pushed an update which add the ability to pass 2 new configuration variables ("alternative_glibc_directory" and "alternative_glibc_version") in order to be able to use a custom GLIBC with Factorio.

The parameters works the same way as Factorio-Init so configuration should be easy.

Cheers !
